fpkg_version: 1
uid: {{cookiecutter.package_uid}}
publisher_uid: {{cookiecutter.publisher_uid}}
name: {{cookiecutter.package_name}}
description: {{cookiecutter.package_description}}
version: 0.1.0
minimum_fme_build: 23224
author:
  name: {{cookiecutter.author}}
package_content:
  transformers:
    - name: {{cookiecutter.transformer_name}}
      version: 1
  python_packages:
    - name: {{cookiecutter.python_module}}
